-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "author" DROP DEFAULT,
ALTER COLUMN "authorImage" DROP DEFAULT,
ALTER COLUMN "message" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
